# Generated by Django 5.2.6 on 2025-10-22 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('apiLink', models.CharField(max_length=100)),
                ('method', models.CharField(choices=[('GET', 'GET'), ('POST', 'POST'), ('PUT', 'PUT'), ('DELETE', 'DELETE')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullName', models.CharField(max_length=50)),
                ('birthDate', models.DateField()),
                ('Email', models.CharField(max_length=50)),
                ('customername', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='photos/%y/%m/%d')),
                ('verification', models.CharField(choices=[('Verified', 'Verified'), ('Not Verified', 'Not Verified')])),
                ('permission', models.ManyToManyField(to='customer.permission')),
            ],
        ),
    ]
