# Generated by Django 5.2.6 on 2025-10-25 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='productsNumber',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
