# Generated by Django 5.2.6 on 2025-09-25 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_color_products_colors'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='availableColors',
        ),
        migrations.RemoveField(
            model_name='products_colors',
            name='colorCount',
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.ManyToManyField(to='product.color'),
        ),
    ]
