# Generated by Django 5.2.6 on 2025-09-25 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_remove_product_availablecolors_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='products_colors',
        ),
    ]
