# Generated by Django 5.2.6 on 2025-09-26 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_delete_products_colors'),
    ]

    operations = [
        migrations.RenameField(
            model_name='color',
            old_name='color',
            new_name='colorName',
        ),
    ]
